<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Company>Cedric-Belin.fr</Company>
		<Copyright>© Cédric Belin</Copyright>
		<Description>A simple yet effective validation engine specifically designed for PowerShell.</Description>
		<Product>Validation for PowerShell</Product>
		<Version>0.7.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblyName>Belin.Validation</AssemblyName>
		<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
		<HotReloadAutoRestart>true</HotReloadAutoRestart>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutDir>../Binaries</OutDir>
		<RootNamespace>Belin.Validation</RootNamespace>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="$(AssemblyName).Tests" />
		<PackageReference Include="System.Management.Automation" Version="7.6.0" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="Validator.fs" />
		<Compile Include="Validators/Base64.fs" />
		<Compile Include="Validators/Count.fs" />
		<Compile Include="Validators/CreditCard.fs" />
		<Compile Include="Validators/Email.fs" />
		<Compile Include="Validators/Enum.fs" />
		<Compile Include="Validators/Range.fs" />
		<Compile Include="Validators/Uri.fs" />
	</ItemGroup>
</Project>
